# Generated by Django 5.1.1 on 2024-09-20 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuotaRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Y', 'Approved'), ('N', 'Denined'), ('W', 'Wait')], default='W', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('sub_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=5)),
                ('sub_name', models.CharField(max_length=100)),
                ('faculty', models.CharField(max_length=100)),
                ('quota_limit', models.IntegerField(default=9999)),
                ('semester', models.CharField(choices=[('semester1', 'Semester1'), ('semester2', 'semester2')], max_length=20)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Close', 'Close')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('stu_id', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('ST', 'Student'), ('AM', 'Admin')], default='ST', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ApproVal',
            fields=[
                ('apprv_id', models.AutoField(primary_key=True, serialize=False)),
                ('approval_date', models.DateField(auto_now_add=True)),
                ('decision', models.CharField(choices=[('Approved', 'Approved'), ('Denied', 'Denied')], max_length=10)),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='myQuataWeb.quotarequest')),
            ],
        ),
        migrations.AddField(
            model_name='quotarequest',
            name='sub_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quota_requests', to='myQuataWeb.subject'),
        ),
        migrations.AddField(
            model_name='quotarequest',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quota_requests', to='myQuataWeb.user'),
        ),
    ]
