# Generated by Django 5.1.1 on 2024-10-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myQuataWeb', '0002_student_alter_quotarequest_user_id_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='faculty',
            field=models.CharField(default='undefined', max_length=255),
            preserve_default=False,
        ),
    ]
