# Generated by Django 5.1.1 on 2024-10-04 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myQuataWeb', '0005_remove_student_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_photos/default.jpg', null=True, upload_to='media/profile_photos/'),
        ),
    ]
