# Generated by Django 5.1.1 on 2024-10-05 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myQuataWeb', '0006_student_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile_photos/'),
        ),
    ]
